### ISSUE TITLE
TWTRComposer does not update its height

### ISSUE THREAD

**Issue by AndrewBarba** [twitter/twitter-kit-ios#1]
TwitterCore 3.1.0
TwitterKit 3.3.0

Current Behavior:

When presenting a tweet with `TWTRComposer` the inner scroll view does not adjust its height or content height when it is given prefilled text, cutting off any text below the fold.

Expected Behavior:

The composer should dynamically update it's height based on tweet length

Sample code:

```swift
        let composer = TWTRComposer()
        composer.setText(content.title)
        composer.setURL(content.src.url)
        composer.show(from: viewController) { result in
            switch result {
            case .done:
                self.trackShare(for: .twitter)
            default:
                break
            }
        }
```

Screens:

![simulator screen shot - iphone x - 2017-12-14 at 14 30 10](https://user-images.githubusercontent.com/1316152/34010760-e10c6d5e-e0db-11e7-8b22-df3be7271592.png)

![simulator screen shot - iphone x - 2017-12-14 at 14 30 23](https://user-images.githubusercontent.com/1316152/34010763-e4533524-e0db-11e7-9271-65e68bccb89b.png)

**Comment by JohnnyTseng** [comment]
Also having this issue with TwitterKit 3.3.0 / iOS 11.2
The text view is not scrollable unless you type some word inside it.

![simulator screen shot - iphone 6s - 2017-12-19 at 12 00 31](https://user-images.githubusercontent.com/2656519/34140228-424ee016-e4b4-11e7-9379-0b167c35879e.png)

**Comment by JaviSoto** [comment]
I just reproduced this in the latest Twitter for iOS app version in the AppStore (as of Dec 20 2017). It uses the same code.

**Comment by linlinyao1** [comment]
same issue here with TwitterKit 3.3.0 on iOS 11.1.2

**Comment by 3a4oT** [comment]
same issue

**Comment by PrakashMaharjan** [comment]
Is this issue fixed?
I am having same issue when shared to twitter from UIActivityViewController also. 
Initially the text height is limited to 3 lines. But when we edit anything like add text or space etc., then the height updates..instantly.
Any suggestions for fixing this initialy while composer is shown with text?

**Comment by evansobkowicz** [comment]
We've merged a fix for this as part of #10, which will be included in the next release.

**Comment by Gouthamdevperk** [comment]
Am having the same scroll alignment issue.  

iOS 11.2 - Simulator
Xcode 9.2

![simulator screen shot - iphone 8 plus - 2018-02-20 at 14 12 35](https://user-images.githubusercontent.com/12889666/36414450-4d7fed02-1648-11e8-8b29-f09732e76123.png)

**Comment by matteinn** [comment]
@evansobkowicz do you have a ballpark estimate for the new release date?

**Comment by Aviral190694** [comment]
I require a twitter share and this issue is still there! Any chances we are going to get this right?

**Comment by JacobJT** [comment]
Why is this marked as closed when it appears that the issue is still in place?

Followed the guide in the ReadMe using Carthage, so should have the most up to date versions.

**Comment by alexviquez** [comment]
This issue persist in:
 TwitterCore (3.2.0)
 TwitterKit (3.4.0)
with Cocoapods any one solution this ?

**Comment by cocoalasca** [comment]
same here
